services:
  consumer:
    build: ./consumer/
    ports:
      - 4000:80
    environment:
      - CLOUDAMQP_HOST=192.168.50.101
      - CLOUDAMQP_PORT=5672
      - RABBITMQ_QUEUE_NAME=test_queue      
      - RABBITMQ_USERNAME=test_user
      - RABBITMQ_PASSWORD=password
      - RABBITMQ_VHOST=/test_host
    volumes:
      - ./consumer/lib:/app/lib
    restart: on-failure
    depends_on:
      - rabbitmq
    links:
      - rabbitmq
  producer:
    build: ./producer/
    ports:
      - 80:80
    environment:
      - CLOUDAMQP_HOST=192.168.50.101
      - CLOUDAMQP_PORT=5672
      - RABBITMQ_QUEUE_NAME=test_queue
      - RABBITMQ_EXCHANGE_NAME=test_exchange
      - RABBITMQ_ROUTE_NAME=test_route
      - RABBITMQ_USERNAME=test_user
      - RABBITMQ_PASSWORD=password
      - RABBITMQ_VHOST=/test_host
    volumes:
      - ./producer/lib:/app/lib
    restart: on-failure
    depends_on:
      - rabbitmq
      - consumer
    links:
      - rabbitmq
      - consumer
  rabbitmq:
    build: ./rabbitmq/
    ports:
      - 8080:15672
      - 5672:5672
